### ISSUE TITLE
This isn't app specific really

### ISSUE THREAD

**Issue by mscotch1** [DineIn2018/dinein#17]
When I followed the instructions in the email to install the dependencies and run the app, I get the typescript error in the following screenshot:
![screenshot from 2018-04-25 11-26-36](https://user-images.githubusercontent.com/25447122/39259306-bad9b22e-487b-11e8-8ff7-111eba87f1db.png)

I don't have an iPad to test, so I won't be able test the app until I figure out how to resolve this or the issue is resolved in the code.

**Comment by kassssc** [comment]
Hey,
Instructions on how to deal with this is included in the e-mail and readme file. Basically you open up any .ts file in the project and save it while the app is running (no need to modify anything). This is caused by a bug in the InteractJS plugin when we transpile our typescript into javascript.
Let me know if you have anymore trouble.

Cheers,
Kass
